---
on: [push, pull_request]
name: default

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        nvim-versions: ['stable', 'nightly']
    name: test
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: ${{ matrix.nvim-versions }}

      - name: Lua action
        uses: mileschou/lua-action@master
        with:
          args: lua -v

      - name: Build
        run: make

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'auto: run build steps'
          file_pattern: lua
